import Head from 'next/head'
import 'devextreme/dist/css/dx.light.css'
import { DataGrid } from 'devextreme-react'
import { employees } from '../employees'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <DataGrid
          id='dataGrid'
          dataSource={employees}
          keyExpr='EmployeeID'></DataGrid>
        <br />
        <a href='/planning'>Planning</a>
      </main>
    </>
  )
}
