import Head from "next/head";
import { Inter } from "next/font/google";
import { Resource } from "@/models/resource";
import useFetch from "../services/fetchData";

let resources: Resource[] = [];

export default function Planning() {
  const fetchState = useFetch<Resource[]>(
    "http://localhost:3000/static/tacticalplanning.json"
  );

  if (fetchState.state === "loading" || fetchState.state === "idle") {
    return <div>Cargando...</div>;
  }

  if (fetchState.state === "error" || !fetchState.data) {
    return <div>Error</div>;
  }

  resources = fetchState.data;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="conte-table">
          {resources.map((res, i) => (
            <table key={i}>
              <thead>
                <tr>
                  <th>Descripción</th>
                  <th>Referencia</th>
                  {res.tacticalPlanning.map((plan, i) => (
                    <th>{plan.forecastedDate.toString()}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                <tr className="conte-table">
                  <td>{res.info.materialDescription}</td>
                  <td>{res.info.reference}</td>
                  {res.tacticalPlanning.map((plan, i) => (
                    <th>{plan.adu}</th>
                  ))}
                </tr>
              </tbody>
            </table>
          ))}
        </div>

        {/* {resources.map((res, i) => (
          <div className="conte-table" key={i}>
            <table>
              <thead>
                <thead>
                  <tr>
                    <th>{res.info.materialDescription}</th>
                    <th>{res.info.reference}</th>
                  </tr>
                </thead>
              </thead>
            </table>
          </div>
        ))} */}

        <br />
        <a href="/">Home</a>
      </main>
    </>
  );
}
