import Head from "next/head";
import { Inter } from "next/font/google";
import { Resource, Plan } from "@/models/resource";
import useFetch from "../services/fetchData";

let resources: Resource[] = [];
let planDates: Plan[] = [];

export default function Planning() {
  const fetchState = useFetch<Resource[]>(
    "http://localhost:3000/static/tacticalplanning.json"
  );

  if (fetchState.state === "loading" || fetchState.state === "idle") {
    return <div>Cargando...</div>;
  }

  if (fetchState.state === "error" || !fetchState.data) {
    return <div>Error</div>;
  }

  resources = fetchState.data;
  planDates = resources[0].tacticalPlanning;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="conte-table">
          <table>
            <thead>
              <tr>
                <th>Descripción</th>
                <th>Referencia</th>
                {planDates.map((plan, i) => (
                  <th key={i}>{plan.forecastedDate.toString()}</th>
                ))}
              </tr>
            </thead>
            <tbody>
                {resources.map((res, i) => (
                  <tr key={i}>
                    <td>{res.info.materialDescription}</td>
                    <td>{res.info.reference}</td>
                    {res.tacticalPlanning.map((plan, i) => (
                      <td key={i}>{plan.adu}</td>
                    ))}
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
